"""empty message

Revision ID: 16c78e609119
Revises: 51cc26f0a7ae
Create Date: 2024-02-14 23:44:19.870049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c78e609119'
down_revision = '51cc26f0a7ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=260),
               type_=sa.String(length=260000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=260000),
               type_=sa.VARCHAR(length=260),
               existing_nullable=False)

    # ### end Alembic commands ###
